Prop.create(title: "Eagles Win", description: "NFL Eagles Win Outright", odds: 1.364, risk: 5.00)
Prop.create(title: "Falcons Win", description: "NFL Falcons Win Outright", odds: 1.699, risk: 5.00)
Prop.create(title: "Patriots Win", description: "NFL Patriots Win Outright", odds: 1.345, risk: 5.00)
Prop.create(title: "Steelers Win", description: "NFL Steelers Win Outright", odds: 1.80, risk: 5.00)
Prop.create(title: "Texans Win", description: "NFL Texans Win Outright", odds: 1.392, risk: 5.00)
Prop.create(title: "Totals Under", description: "Chiefs/49ers Game Total Goes Under 55", odds: 1.909, risk: 5.00)
Prop.create(title: "Totals Under", description: "Panthers/Bengals Game Total Goes Under 43.5", odds: 1.909, risk: 5.00)
Prop.create(title: "Totals Under", description: "Dolphins/Raiders Game Total Goes Under 44.5", odds: 1.909, risk: 5.00)
Prop.create(title: "Totals Over", description: "Eagles/Colts Game Total Goes Over 47", odds: 1.909, risk: 5.00)
Prop.create(title: "Totals Over", description: "Ravens/Broncos Game Total Goes Over 44.5", odds: 1.909, risk: 5.00)
